### ISSUE TITLE
This project is a bad idea.

### ISSUE THREAD

**Issue by MegaTeam89** [RegularSpark/wrapper-offline-php#1]
I'm not writing this to be mean or act like I'm flexing or anything; this is, in my opinion, a waste of time. GoAnimate's original API was written in AJAX (Asynchronous JavaScript and XML), and throwing that all out the window to port it to PHP looks like masochism. During my time "rewriting" the code for my wrapper project and observing how both PHP and NodeJS work, it's abundantly clear PHP is not suited for this use case. PHP is too clunky and has no way of handling asynchronous code; neither is it a good choice for handling multiple requests (which GoAnimate makes a lot of). Thus,  This "rewrite" is nothing more than making API slower and clunkier to use. I believe it is possible to "rewrite" it in PHP, but the whole point of a "rewrite" is to make things more efficient and faster. PHP in the backend doesn't execute as fast and has to wait to fulfill other processes. If I were you, I'd go back to refactoring the JS code in the original Wrapper project. Again, not to be rude, just being brutally honest here.

**Comment by RegularSpark** [comment]
¯\_(ツ)_/¯

**Comment by MegaTeam89** [comment]
you forgot the "\" + ratio + you fell off

**Comment by MegaTeam89** [comment]
backslashes don't work on github issues + ratio + you fell off

**Comment by RegularSpark** [comment]
ratio declined

**Comment by PoleyMagik** [comment]
nah ratio granted
